apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
  namespace: minio
spec:
  ports:
  - name: app
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: minio
  type: ClusterIP
