# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: minio
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/ViniciusPilan/devops-lab.git
#     targetRevision: main
#     path: ops/minio
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: minio

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    chart: operator
    repoURL: https://operator.min.io
    targetRevision: 7.1.1
  destination:
    name: "in-cluster"
    namespace: minio
