apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  sources:
    - path: ops/minio
      repoURL: https://github.com/ViniciusPilan/devops-lab.git
      targetRevision: main
  destination:
    name: "in-cluster"
    namespace: minio
