apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metrics-visualizer
  name: metrics-visualizer
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-visualizer
  template:
    metadata:
      labels:
        app: metrics-visualizer
    spec:
      containers:
      - image: amazon/aws-cli
        name: get-dataset
        envFrom:
        - secretRef:
            name: app-credentials
        volumeMounts:
        - name: app-folder
          mountPath: /app/data
        command: ["/bin/bash", "-c"]
        args: ["while true; do aws --endpoint-url http://minio.minio.svc:9000 s3 cp s3://app/metrics.csv /app/data/metrics.csv & sleep 3600; done"]
      - image: metrics-visualizer:1.0.0
        name: metrics-visualizer
        env:
        - name: DATA_PATH
          value: "/app/data"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-folder
          mountPath: /app/data
      volumes:
      - name: app-folder
        emptyDir: {}
