apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metrics-visualizer
  name: metrics-visualizer
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-visualizer
  strategy: {}
  template:
    metadata:
      labels:
        app: metrics-visualizer
    spec:
      initContainers:
      - image: amazon/aws-cli
        name: get-dataset
        envFrom:
        - secretRef:
            name: app-credentials
        command: ["aws", "--endpoint-url", "http://minio.minio.svc:9000", "s3", "cp", "s3://app/metrics.csv", "/app/metrics.csv"]
      # Create a container to get the metrics.csv
      containers:
      - image: metrics-visualizer:1.0.0
        name: metrics-visualizer
        ports:
        - containerPort: 8080
status: {}
