apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metrics-visualizer
  name: metrics-visualizer
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-visualizer
  strategy: {}
  template:
    metadata:
      labels:
        app: metrics-visualizer
    spec:
      # initContainers:
      # Create a container to get the metrics.csv
      containers:
      - image: metrics-visualizer:1.0.0
        name: metrics-visualizer
        envFrom:
        - secretRef:
            name: app-credentials
        env:
        - name: BUCKET_HOST
          value: "minio.minio.svc:9000"
        ports:
        - containerPort: 8080
status: {}
