apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metrics-visualizer
  name: metrics-visualizer
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-visualizer
  strategy: {}
  template:
    metadata:
      labels:
        app: metrics-visualizer
    spec:
      initContainers:
      - image: amazon/aws-cli
        name: get-dataset
        envFrom:
        - secretRef:
            name: app-credentials
        command: ["aws", "--endpoint-url", "http://minio.minio.svc:9000", "s3", "cp", "s3://app/metrics.csv", "/app/data/metrics.csv"]
        volumeMounts:
        - name: app-folder
          mountPath: /app/data
      containers:
      - image: metrics-visualizer:1.0.0
        name: metrics-visualizer
        env:
        - name: DATA_PATH
          value: "/app/data"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-folder
          mountPath: /app/data
      volumes:
      - name: app-folder
        emptyDir: {}
status: {}
