apiVersion: v1
kind: Service
metadata:
  labels:
    app: metrics-visualizer
  name: metrics-visualizer
  namespace: app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: metrics-visualizer
  type: ClusterIP
